availableSecrets:
  secretManager:
    - versionName: projects/772190012442/secrets/APPLICATION/versions/latest
      env: SECRET_ENV

steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SECRET_ENV" > src/main/resources/application.yml
    secretEnv: ['SECRET_ENV']

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-repo/planpal',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-repo/planpal']

  # 기존 VM에 컨테이너 업데이트
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['compute', 'instances',
           'update-container', 'planpal-vm',
           '--container-image',
           'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-repo/planpal',
           '--zone', 'asia-northeast3-c']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-northeast3'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast3-c'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-repo/planpal'
