apiVersion: apps/v1
kind: Deployment
metadata:
  name: planpal-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planpal-server
  template:
    metadata:
      labels:
        app: planpal-server
    spec:
      containers:
        - name: planpal-server-container
          image: asia-northeast3-docker.pkg.dev/k8s-test-464207/k8s-server-registry/planpal-server
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secrets-volume
              mountPath: "/app/resources"
              readOnly: true
      volumes:
        - name: secrets-volume
          secret:
            secretName: planpal-config-secret