spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  ai:
    vertex:
      ai:
        gemini:
          project-id: "gemini-ai-455106"
          location: "us-central1"
          chat:
            options:
              model: gemini-2.0-flash
  config:
    import: classpath:secret.yml

