spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planpal
    username: root
    password: zx8320
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: classpath:secret.yml

